# Cloudflare Workers configuration
name = "kapsules-worker"
compatibility_date = "2025-06-15"

# Default (development) environment
workers_dev = true

# Account ID (replace with your Cloudflare account ID)
account_id = "<CLOUDFLARE_ACCOUNT_ID>"

# Development environment config
[env.dev]
name = "kapsules-dev"
route = "${projectName}.genr8.dev/*"

# Production environment config
[env.production]
name = "kapsules by genr8"
route = "genr8.dev/*"
